@startuml
(*)  --> "user signs in"
If "feature <b>Easter egg</b> is enabled" then
-> [Yes] "show easter egg
collect metrics"
--> "display user info"
else
--> [No] "display user info,
old version"
Endif
@enduml
